name: "Build QMK Firmware"

env:
  qmk-version: 1.1.5

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Install Dependencies"
        run: |
          pip3 install "qmk==${{ env.qmk-version }}"
          qmk setup -y -H qmk_firmware
          sudo apt install stow
      - name: "Clone Configuration"
        uses: actions/checkout@v4
        with:
          path: 'qmk'
      - name: "Build"
        run: |
          cd qmk
          repoQmk=$GITHUB_WORKSPACE/qmk_firmware make
      - name: "Upload firmware binary"
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: ${{ github.workspace }}/qmk_firmware/*.uf2
